# Generated by Django 4.1.2 on 2022-11-01 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name_plural': 'Prdouct Categorys '},
        ),
    ]
